#!/bin/bash   
# Written by Simon Sinding - 2016 Github.com/TheSinding/
SCREENSHOT_DIR="$HOME/screenshots/"
SCROT_FILE_OPTIONS="%Y-%m-%d_\$wx\$h_scrot.png"
hash scrot 2>/dev/null ||
{
	echo >&2 "Error: Scrot is required but it's not installed.  Aborting.";
	exit 1; 
}

hash pastey 2>/dev/null || 
{ 
	echo >&2 "Error: Pastey is required but it's not installed, see https://github.com/TheSinding/pastey/.  Aborting."; 
	exit 1; 
}
if [ ! -d $SCREENSHOT_DIR ]; then
	echo "Info: $HOME/screenshots/ does not exists, creating it!"
	mkdir $SCREENSHOT_DIR
fi
HELP(){
		echo "Written by Simon Sinding - 2016 - Github.com/TheSinding/"
		echo "Usage: klibbert [OPTIONS]"
		echo "	-h, 	Shows this help"
		echo "	-f,		Fullscreen screenshot"
		echo "	-r,		Region screenshot"
		exit 1
}
OPEN(){
	if [ $1 ]; then 
		xdg-open $1
	fi
	exit 1
}
while getopts ":frh" opt; do
  case $opt in
		h)
			HELP
    	;;
    f)
			url=$(scrot $SCREENSHOT_DIR$SCROT_FILE_OPTIONS -e 'pastey -f $f' 2>&1)
			OPEN $url	
    	;;
		r)
			url=$(scrot -s $SCREENSHOT_DIR$SCROT_FILE_OPTIONS -e 'pastey -f $f' 2>&1)
			OPEN $url	
			;;
		\?)
			echo "Error: -$OPTARG is an invalid option"
			HELP
			;;
  esac
done

if (($# == 0)); then
  HELP
fi
